name: Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - release/**
  issue_comment:
    types: [created, edited]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [member]
    permissions:
      pull-requests: write
    timeout-minutes: 10
    if: needs.member.outputs.valid == 'true'
    outputs:
      repo_name: ${{ steps.pr_data.outputs.repo_name }}
      ref: ${{ steps.pr_data.outputs.ref }}
    steps:
      - name: Comment PR for Sim test started
        uses: crypto-org-chain/actions-pull-request-add-comment@master
        if: github.event_name == 'issue_comment'
        with:
          message: |
            Simulation tests started and triggered by `/runsim`. 
            Will update here when it succeeds or fails.
            Can further check progress [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Comment PR informations
        id: pr_data
        if: github.event_name == 'issue_comment'
        run: |
          echo "repo_name=${{ fromJson(steps.request.outputs.data).head.repo.full_name }}" >> $GITHUB_OUTPUT
          comment_hash=`echo ${{ github.event.comment.body }} | cut -d' ' -f2` # get commit hash if any
          if [[ "${comment_hash}" == "/runsim" ]]; then 
            # use default head ref
            echo "ref=${{ fromJson(steps.request.outputs.data).head.ref }}" >> $GITHUB_OUTPUT
          else
            # use comment provided ref
            echo "ref=${comment_hash}" >> $GITHUB_OUTPUT
          fi
