name: Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - release/**
  issue_comment:
    types: [created, edited]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 10
    outputs:
      repo_name: ${{ steps.pr_data.outputs.repo_name }}
      ref: ${{ steps.pr_data.outputs.ref }}
    steps:
      - name: Get Comment PR informations
        id: pr_data
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOP_SECRET }}
        run: |
          echo "OKKKKKKK=======START============"
          echo "$GITHUB_TOKEN"
          echo "=============xxxDonexxx========="
