name: Build

on:
  pull_request:
  merge_group:
  push:
    branches:
      - master
      - release/**
  issue_comment:
    types: [created, edited]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 10
    outputs:
      repo_name: ${{ steps.pr_data.outputs.repo_name }}
      ref: ${{ steps.pr_data.outputs.ref }}
    steps:
      - name: Get Comment PR informations
        id: pr_data
        if: github.event_name == 'issue_comment'
        run: |
          echo "repo_name=${{ github.event.comment.body }}"
          echo "repo_name=${{ github.event.comment.body }}" >> $GITHUB_OUTPUT
          comment_hash=`echo ${{ github.event.comment.body }} | cut -d' ' -f2` # get commit hash if any
          if [[ "${comment_hash}" == "/runsim" ]]; then 
            echo "yeah Mr.White"
          else
            # use comment provided ref
            echo "ref=${comment_hash}" >> $GITHUB_OUTPUT
          fi
